# Configuration file for http://goreleaser.com

builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
      - GOFLAGS=-mod=vendor

archives:
  - files:
      - plugin.yaml

changelog:
  sort: asc
